build:
  tags:
    - docker
  image: registry.gitlab.com/famedly/infra/containers/buildah
  stage: build
  variables:
    VERSION: 4.5.3-r0
  before_script:
    - buildah login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - buildah bud --pull --build-arg VERSION=${VERSION} --manifest "${CI_REGISTRY_IMAGE}" --platform linux/amd64 .
    - buildah push -f v2s2 --all "${CI_REGISTRY_IMAGE}"
    - buildah push -f v2s2 --all "${CI_REGISTRY_IMAGE}" "docker://${CI_REGISTRY_IMAGE}:v${VERSION}"

